Resolve compatibility problems with change python version in ubuntu upstream repos: manual installation of python3.9

diff --git a/Scripts/ml-agents-docker/Dockerfile b/Scripts/ml-agents-docker/Dockerfile
--- a/Scripts/ml-agents-docker/Dockerfile
+++ b/Scripts/ml-agents-docker/Dockerfile
@@ -19,7 +19,9 @@ ENV LANG en_US.UTF-8
 ENV LANGUAGE en_US:en
 ENV LC_ALL en_US.UTF-8
 
-RUN /tmp/scripts/apt_install.sh ca-certificates sudo git locales tzdata
+RUN /tmp/scripts/apt_install.sh ca-certificates sudo git locales tzdata \
+                                software-properties-common dirmngr apt-transport-https lsb-release \
+                                curl
 RUN /tmp/scripts/setup_locale.sh
 RUN /tmp/scripts/setup_timezone.sh
 
@@ -30,6 +32,12 @@ RUN usermod -aG sudo $USER_NAME
 
 # copy the other scripts - split up to reduce rebuild times
 COPY scripts/ /tmp/scripts/
-RUN /tmp/scripts/apt_install.sh python3 python3-pip python3-venv
+
+# mlagents 0.30.0 requires Python Version >=3.8.13,<=3.10.8 (Ubuntu ships with 3.10.12)
+# the add-apt-repository fails for some reason, so ignore the error, since the rest still works
+RUN apt update && apt upgrade -y
+RUN add-apt-repository -n -y ppa:deadsnakes/ppa || exit 0
+# should install 3.9.17; 3.10 is available via ubuntu upstream, but it is 3.10.12
+RUN /tmp/scripts/apt_install.sh python3.9 python3.9-venv
 
 ENTRYPOINT [ "/bin/bash", "/tmp/scripts/entrypoint.sh", "${USER_NAME}" ]
